name: Code Analysis

on:
  push:
    branches:
      - v3
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - run: npm i && npm run lint